import Head from "next/head";

import NextHoliday from "@/components/NextHoliday";
import Image from "next/image";

import GHFlag from "@/assets/gh-flag.svg";

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Holidays Ghana</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-100 h-full flex flex-col items-center justify-center gap-8 font-inter">
        <Image src={GHFlag} alt="The flag of Ghana" width={150} />
        <NextHoliday holidays={props.data} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const data = await fetch(
    "https://calendarific.com/api/v2/holidays?&api_key=b1b631fa64ca7a2c63401122c0703842ed1c004b&country=GH&year=2023"
  );
  const response = await data.json();

  return {
    props: {
      data: response.response,
    },
  };
}
