import Head from "next/head";

import isFuture from "date-fns/isFuture";
import { DateTime, Interval } from "luxon";

import NextHoliday from "@/components/NextHoliday";
import Image from "next/image";
import GHFlag from "@/assets/gh-flag.svg";
import { useState } from "react";
import AllHolidays from "@/components/AllHolidays";

export default function Home(props) {
    /* Taking the array of holidays and adding a new property to each object in the array. */
    const [showAll, setShowAll] = useState(false);

    const handleButtonClick = () => {
        setShowAll((prevShowAll) => !prevShowAll);
    };

    const checkFuture = (year, month, day) => {
        const now = DateTime.utc();
        const holidayDate = DateTime.utc(year, month, day);

        const interval = Interval.fromDateTimes(now, holidayDate);
        const intervalInDays = Math.ceil(interval.length("day"));
        if (intervalInDays >= 0) {
            return true;
        }

        return false;
    };

    const formattedHolidays = props.data.holidays.map((holiday) => {
        return {
            ...holiday,
            isFuture: checkFuture(
                holiday.date.datetime.year,
                holiday.date.datetime.month,
                holiday.date.datetime.day
            ),
        };
    });

    return (
        <>
            <Head>
                <title>Important Days Ghana</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="bg-gray-100 h-full flex flex-col items-center justify-center gap-8 font-inter grow p-4">
                <button
                    onClick={handleButtonClick}
                    className="bg-slate-700 p-3 rounded font-bold text-white hover:bg-slate-500"
                >
                    {showAll
                        ? "Show Closest Holiday"
                        : "Show All Important Days"}
                </button>
                <Image src={GHFlag} alt="The flag of Ghana" width={150} />
                {showAll ? (
                    <AllHolidays holidayData={formattedHolidays} />
                ) : (
                    <NextHoliday formattedHolidays={formattedHolidays} />
                )}
            </main>
        </>
    );
}

export async function getStaticProps() {
    const data = await fetch(
        "https://calendarific.com/api/v2/holidays?&api_key=b1b631fa64ca7a2c63401122c0703842ed1c004b&country=GH&year=2023"
    );
    const response = await data.json();

    return {
        props: {
            data: response.response,
        },
    };
}
